// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wms.Api.Data.Migrations;

[DbContext(typeof(WmsDbContext))]
[Migration("20260831084757_AddUniqueProductBarcode")]
partial class AddUniqueProductBarcode
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Wms.Api.Domain.Entities.Product", entity =>
        {
            entity.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(entity.Property<int>("Id"));

            entity.Property<string>("Barcode")
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            entity.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("datetime2");

            entity.Property<bool>("IsActive")
                .HasColumnType("bit");

            entity.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            entity.Property<string>("Sku")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            entity.HasKey("Id");

            entity.HasIndex("Barcode")
                .IsUnique()
                .HasFilter("[Barcode] IS NOT NULL");

            entity.HasIndex("Sku")
                .IsUnique();

            entity.ToTable("Products");
        });
#pragma warning restore 612, 618
    }
}
